version: '3.7'

services:
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - airflow_net

  webserver:
    image: apache/airflow:2.9.1
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DB_URL}
      - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW_SECRET_KEY}
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./etl:/opt/airflow/etl
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - airflow_net

  scheduler:
    image: apache/airflow:2.9.1
    restart: always
    depends_on:
      - webserver
      - postgres
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${AIRFLOW_DB_URL}
      - PYTHONPATH=/opt/airflow
    volumes:
      - ./etl:/opt/airflow/etl
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    networks:
      - airflow_net

volumes:
  postgres-db-volume:

networks:
  airflow_net:
    driver: bridge